const RED_FLAG_KEYWORDS = [
  { keyword: 'heart attack', score: 10, next_step: 'Call emergency services immediately.' },
  { keyword: 'stroke', score: 10, next_step: 'Call emergency services immediately.' },
  { keyword: 'cauda equina', score: 10, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'paralysis', score: 10, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'thunderclap headache', score: 10, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'suicidal', score: 10, next_step: 'Please reach out to a mental health crisis line or emergency services immediately.' },
  { keyword: 'anaphylaxis', score: 10, next_step: 'Use EpiPen if available and call emergency services immediately.' },
  { keyword: 'severe allergic reaction', score: 10, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'cannot breathe', score: 10, next_step: 'Call emergency services immediately.' },
  { keyword: 'choking', score: 10, next_step: 'Get immediate help or call emergency services.' },
  { keyword: 'chest pain', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'chest tightness', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'chest pressure', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'difficulty breathing', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'loss of bladder', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'bladder control', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'loss of bowel', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'bowel control', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'saddle anaesthesia', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'saddle anesthesia', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'worst headache', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'loss of consciousness', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'seizure', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'vision loss', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'slurred speech', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'facial drooping', score: 9, next_step: 'Seek emergency medical attention immediately — possible stroke.' },
  { keyword: 'coughing blood', score: 9, next_step: 'Seek urgent medical attention.' },
  { keyword: 'vomiting blood', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'self harm', score: 9, next_step: 'Please contact a mental health professional or crisis service immediately.' },
  { keyword: 'self-harm', score: 9, next_step: 'Please contact a mental health professional or crisis service immediately.' },
  { keyword: 'want to die', score: 9, next_step: 'Please reach out to a mental health crisis line or emergency services immediately.' },
  { keyword: 'severe shortness of breath', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'crushing chest pain', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'sudden severe headache', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'unconscious', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'severe bleeding', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'massive bleeding', score: 9, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'shortness of breath', score: 8, next_step: 'Seek urgent medical attention.' },
  { keyword: 'numbness in arm', score: 8, next_step: 'Consult a medical professional urgently.' },
  { keyword: 'arm numbness', score: 8, next_step: 'Consult a medical professional urgently.' },
  { keyword: 'urinary incontinence', score: 8, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'fever with back pain', score: 8, next_step: 'See a doctor urgently.' },
  { keyword: 'fever with neck pain', score: 8, next_step: 'See a doctor urgently.' },
  { keyword: 'car accident', score: 8, next_step: 'Seek medical evaluation promptly.' },
  { keyword: 'severe headache', score: 8, next_step: 'Seek medical advice promptly.' },
  { keyword: 'sudden headache', score: 8, next_step: 'Seek medical attention promptly.' },
  { keyword: 'fainting', score: 8, next_step: 'Seek medical attention promptly.' },
  { keyword: 'blackout', score: 8, next_step: 'Seek medical attention promptly.' },
  { keyword: 'speech difficulty', score: 8, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'blood in urine', score: 8, next_step: 'See a doctor urgently.' },
  { keyword: 'blood in stool', score: 8, next_step: 'See a doctor urgently.' },
  { keyword: 'severe abdominal pain', score: 8, next_step: 'Seek urgent medical attention.' },
  { keyword: 'unable to move', score: 8, next_step: 'Seek medical evaluation promptly.' },
  { keyword: 'cannot move', score: 8, next_step: 'Seek medical evaluation promptly.' },
  { keyword: 'tumor', score: 8, next_step: 'Consult your healthcare provider promptly.' },
  { keyword: 'tumour', score: 8, next_step: 'Consult your healthcare provider promptly.' },
  { keyword: 'sudden vision loss', score: 8, next_step: 'Seek emergency medical attention immediately.' },
  { keyword: 'sudden hearing loss', score: 8, next_step: 'Seek urgent medical attention.' },
  { keyword: 'severe dizziness', score: 8, next_step: 'Seek medical attention promptly.' },
  { keyword: 'severe vertigo', score: 8, next_step: 'Seek medical attention promptly.' },
  { keyword: 'high fever', score: 8, next_step: 'See a doctor urgently.' },
  { keyword: 'fever over 39', score: 8, next_step: 'See a doctor urgently.' },
  { keyword: 'fever above 102', score: 8, next_step: 'See a doctor urgently.' },
  { keyword: 'severe burn', score: 8, next_step: 'Seek urgent medical attention.' },
  { keyword: 'third degree burn', score: 8, next_step: 'Seek urgent medical attention.' },
  { keyword: 'concussion', score: 8, next_step: 'Seek immediate medical evaluation for head injury.' },
  { keyword: 'head injury', score: 8, next_step: 'Seek immediate medical evaluation for head injury.' },
  { keyword: 'fracture', score: 8, next_step: 'Seek immediate medical attention for suspected fracture.' },
  { keyword: 'broken bone', score: 8, next_step: 'Seek immediate medical attention for suspected fracture.' },
  { keyword: 'dislocation', score: 8, next_step: 'Seek immediate medical attention for dislocation.' },
  { keyword: 'dislocated', score: 8, next_step: 'Seek immediate medical attention for dislocation.' },
  { keyword: 'asthma attack', score: 8, next_step: 'Use rescue inhaler and seek immediate medical attention.' },
  { keyword: 'chest heaviness', score: 8, next_step: 'Seek medical attention for chest symptoms.' },
  { keyword: 'numbness in leg', score: 7, next_step: 'Consult a medical professional urgently.' },
  { keyword: 'leg numbness', score: 7, next_step: 'Consult a medical professional urgently.' },
  { keyword: 'unexplained weight loss', score: 7, next_step: 'See a doctor for further investigation.' },
  { keyword: 'sudden weight loss', score: 7, next_step: 'See a doctor for further investigation.' },
  { keyword: 'trauma', score: 7, next_step: 'Consult a physiotherapist or doctor.' },
  { keyword: 'fall injury', score: 7, next_step: 'Consult a physiotherapist or doctor.' },
  { keyword: 'loss of balance', score: 7, next_step: 'Consult a healthcare provider promptly.' },
  { keyword: 'difficulty walking', score: 7, next_step: 'Consult a healthcare provider promptly.' },
  { keyword: 'loss of coordination', score: 7, next_step: 'Seek medical advice promptly.' },
  { keyword: 'blurred vision', score: 7, next_step: 'Seek medical attention promptly.' },
  { keyword: 'double vision', score: 7, next_step: 'Seek medical attention promptly.' },
  { keyword: 'weakness in arm', score: 7, next_step: 'Seek medical attention promptly.' },
  { keyword: 'weakness in leg', score: 7, next_step: 'Seek medical attention promptly.' },
  { keyword: 'lump', score: 7, next_step: 'Have any new lumps assessed by a healthcare provider.' },
  { keyword: 'new lump', score: 7, next_step: 'Have any new lumps assessed by a healthcare provider.' },
  { keyword: 'deep bone pain', score: 7, next_step: 'Consult a healthcare provider promptly.' },
  { keyword: 'spinal cord', score: 7, next_step: 'Seek urgent medical evaluation.' },
  { keyword: 'persistent vomiting', score: 7, next_step: 'Seek medical attention.' },
  { keyword: 'jaw pain', score: 7, next_step: 'Consult a healthcare provider — may indicate cardiac issues.' },
  { keyword: 'sudden jaw pain', score: 7, next_step: 'Consult a healthcare provider — may indicate cardiac issues.' },
  { keyword: 'persistent fever', score: 7, next_step: 'Consult a healthcare provider promptly.' },
  { keyword: 'fever lasting days', score: 7, next_step: 'Consult a healthcare provider promptly.' },
  { keyword: 'night sweats', score: 7, next_step: 'Schedule a medical consultation.' },
  { keyword: 'unexplained night sweats', score: 7, next_step: 'Schedule a medical consultation.' },
  { keyword: 'sudden severe pain', score: 7, next_step: 'Seek medical attention promptly.' },
  { keyword: 'excruciating pain', score: 7, next_step: 'Seek medical attention promptly.' },
  { keyword: 'unbearable pain', score: 7, next_step: 'Seek medical attention promptly.' },
  { keyword: 'torn ligament', score: 7, next_step: 'Consult a sports medicine professional or orthopedic specialist.' },
  { keyword: 'ligament tear', score: 7, next_step: 'Consult a sports medicine professional or orthopedic specialist.' },
  { keyword: 'meniscus tear', score: 7, next_step: 'Consult an orthopedic specialist promptly.' },
  { keyword: 'acl', score: 7, next_step: 'Consult an orthopedic specialist immediately.' },
  { keyword: 'pcl', score: 7, next_step: 'Consult an orthopedic specialist.' },
  { keyword: 'whiplash', score: 7, next_step: 'Seek medical evaluation following neck injury.' },
  { keyword: 'herniated disc', score: 7, next_step: 'Consult a spinal specialist or physiotherapist.' },
  { keyword: 'slipped disc', score: 7, next_step: 'Consult a spinal specialist or physiotherapist.' },
  { keyword: 'chest discomfort', score: 7, next_step: 'Consult a healthcare provider about chest symptoms.' },
  { keyword: 'irregular heartbeat', score: 7, next_step: 'Consult a healthcare provider about heart rhythm.' },
  { keyword: "can't catch breath", score: 7, next_step: 'Seek medical attention for breathing difficulties.' },
  { keyword: 'mole changes', score: 7, next_step: 'Have mole changes assessed promptly by a dermatologist.' },
  { keyword: 'suspicious mole', score: 7, next_step: 'Have suspicious moles assessed promptly by a dermatologist.' },
  { keyword: 'cancer', score: 9, next_step: 'Consult your oncologist or healthcare provider immediately.' },
  { keyword: 'rapid weight loss', score: 6, next_step: 'See a doctor for further investigation.' },
  { keyword: 'cold sweats', score: 6, next_step: 'Schedule a medical consultation.' },
  { keyword: 'profuse sweating', score: 6, next_step: 'Schedule a medical consultation.' },
  { keyword: 'radiating pain', score: 6, next_step: 'Book an appointment with your physiotherapist.' },
  { keyword: 'pain radiating', score: 6, next_step: 'Book an appointment with your physiotherapist.' },
  { keyword: 'pain shooting', score: 6, next_step: 'Book an appointment with your physiotherapist.' },
  { keyword: 'shooting pain', score: 6, next_step: 'Book an appointment with your physiotherapist.' },
  { keyword: 'stabbing pain', score: 6, next_step: 'Monitor closely and consult if worsening.' },
  { keyword: 'dizziness', score: 6, next_step: 'Consult a healthcare provider.' },
  { keyword: 'vertigo', score: 6, next_step: 'Consult a healthcare provider.' },
  { keyword: 'muscle weakness', score: 6, next_step: 'Consult a healthcare provider.' },
  { keyword: 'significant swelling', score: 6, next_step: 'Consult a healthcare provider.' },
  { keyword: 'redness and swelling', score: 6, next_step: 'Consult a healthcare provider.' },
  { keyword: 'warmth and swelling', score: 6, next_step: 'Consult a healthcare provider.' },
  { keyword: 'pain at night', score: 6, next_step: 'Schedule a consultation with your healthcare provider.' },
  { keyword: 'night pain', score: 6, next_step: 'Schedule a consultation with your healthcare provider.' },
  { keyword: 'waking pain', score: 6, next_step: 'Schedule a consultation with your healthcare provider.' },
  { keyword: 'bone pain', score: 6, next_step: 'Consult a healthcare provider if unexplained.' },
  { keyword: 'disc herniation', score: 6, next_step: 'Consult a physiotherapist or spinal specialist.' },
  { keyword: 'bulging disc', score: 6, next_step: 'Consult a physiotherapist or spinal specialist.' },
  { keyword: 'nerve compression', score: 6, next_step: 'Consult a physiotherapist or doctor.' },
  { keyword: 'severe nausea', score: 6, next_step: 'Consult a healthcare provider if persistent.' },
  { keyword: 'extreme fatigue', score: 6, next_step: 'Consult a healthcare provider.' },
  { keyword: 'sudden fatigue', score: 6, next_step: 'Consult a healthcare provider.' },
  { keyword: 'neck stiffness', score: 6, next_step: 'Consult a healthcare provider, especially if with fever.' },
  { keyword: 'stiff neck', score: 6, next_step: 'Consult a healthcare provider, especially if with fever.' },
  { keyword: 'spreading rash', score: 6, next_step: 'Seek medical attention for spreading rashes.' },
  { keyword: 'hopeless', score: 6, next_step: 'Please speak with your healthcare provider or a mental health professional.' },
  { keyword: 'numbness', score: 6, next_step: 'Consult a healthcare provider if numbness persists.' },
  { keyword: 'burning pain', score: 6, next_step: 'Consult a healthcare provider for burning pain.' },
  { keyword: 'weakness', score: 6, next_step: 'Consult a healthcare provider about muscle weakness.' },
  { keyword: 'persistent headache', score: 6, next_step: 'Consult a healthcare provider about persistent headaches.' },
  { keyword: 'frequent headaches', score: 6, next_step: 'Consult a healthcare provider about frequent headaches.' },
  { keyword: 'recurring headache', score: 6, next_step: 'Consult a healthcare provider about recurring headaches.' },
  { keyword: 'persistent cough', score: 6, next_step: 'Consult a healthcare provider about persistent cough.' },
  { keyword: 'chronic cough', score: 6, next_step: 'Consult a healthcare provider about chronic cough.' },
  { keyword: 'joint swelling', score: 6, next_step: 'Consult a healthcare provider about joint swelling.' },
  { keyword: 'severe joint pain', score: 6, next_step: 'Consult a healthcare provider promptly.' },
  { keyword: 'rotator cuff', score: 6, next_step: 'Consult a physiotherapist or sports medicine professional.' },
  { keyword: 'mcl', score: 6, next_step: 'Consult a sports medicine professional.' },
  { keyword: 'achilles', score: 6, next_step: 'Consult a physiotherapist or sports medicine professional.' },
  { keyword: 'carpal tunnel', score: 6, next_step: 'Consult a healthcare provider about carpal tunnel syndrome.' },
  { keyword: 'pinched nerve', score: 6, next_step: 'Consult a physiotherapist or neurologist.' },
  { keyword: 'trapped nerve', score: 6, next_step: 'Consult a physiotherapist or neurologist.' },
  { keyword: 'wheezing', score: 6, next_step: 'Consult a healthcare provider about breathing difficulties.' },
  { keyword: 'tight chest', score: 6, next_step: 'Consult a healthcare provider about chest tightness.' },
  { keyword: 'shallow breathing', score: 6, next_step: 'Consult a healthcare provider about breathing pattern.' },
  { keyword: 'rapid breathing', score: 6, next_step: 'Consult a healthcare provider about breathing changes.' },
  { keyword: 'rapid heartbeat', score: 6, next_step: 'Monitor and consult if persistent or concerning.' },
  { keyword: 'racing heart', score: 6, next_step: 'Monitor and consult if persistent or concerning.' },
  { keyword: 'palpitations', score: 6, next_step: 'Monitor and consult if frequent or concerning.' },
  { keyword: 'heart pounding', score: 6, next_step: 'Monitor and consult if frequent or severe.' },
  { keyword: 'heart skipping', score: 6, next_step: 'Monitor and consult if frequent.' },
  { keyword: 'vomiting', score: 6, next_step: 'Monitor and seek medical attention if persistent.' },
  { keyword: 'panic', score: 6, next_step: 'Consider speaking with a mental health professional.' },
  { keyword: 'panic attack', score: 6, next_step: 'Consider speaking with a mental health professional.' },
  { keyword: 'depression', score: 6, next_step: 'Please speak with a mental health professional.' },
  { keyword: 'depressed', score: 6, next_step: 'Please speak with a mental health professional.' },
  { keyword: 'skin lesion', score: 6, next_step: 'Have skin lesions assessed by a healthcare provider.' },
  { keyword: 'tingling', score: 5, next_step: 'Monitor and consult if persistent.' },
  { keyword: 'pins and needles', score: 5, next_step: 'Monitor and consult if persistent.' },
  { keyword: 'burning sensation', score: 5, next_step: 'Monitor and consult if persistent.' },
  { keyword: 'sharp pain', score: 5, next_step: 'Monitor and consult if not improving.' },
  { keyword: 'migraine', score: 5, next_step: 'Consult your healthcare provider about management.' },
  { keyword: 'swelling', score: 5, next_step: 'Monitor and consult if persistent or worsening.' },
  { keyword: 'abdominal pain', score: 5, next_step: 'Consult a healthcare provider if persistent.' },
  { keyword: 'constant pain', score: 5, next_step: 'Consult your healthcare provider.' },
  { keyword: 'sciatica', score: 5, next_step: 'Consult a physiotherapist or doctor.' },
  { keyword: 'rash', score: 5, next_step: 'Have unexplained rashes assessed by a healthcare provider.' },
  { keyword: 'pain', score: 5, next_step: 'Monitor pain and consult if it worsens or persists.' },
  { keyword: 'burning', score: 5, next_step: 'Monitor burning sensation and consult if persistent.' },
  { keyword: 'leg pain', score: 5, next_step: 'Monitor leg pain and consult if it worsens.' },
  { keyword: 'back pain', score: 5, next_step: 'Monitor back pain and consult if it persists.' },
  { keyword: 'neck pain', score: 5, next_step: 'Monitor neck pain and consult if it persists.' },
  { keyword: 'arm pain', score: 5, next_step: 'Monitor arm pain and consult if it persists.' },
  { keyword: 'headache', score: 5, next_step: 'Monitor headache and consult if frequent or severe.' },
  { keyword: 'nausea', score: 5, next_step: 'Monitor nausea and consult if persistent.' },
  { keyword: 'fatigue', score: 5, next_step: 'Monitor fatigue and consult if unexplained or severe.' },
  { keyword: 'stiffness', score: 5, next_step: 'Monitor stiffness and consult if limiting function.' },
  { keyword: 'knee pain', score: 5, next_step: 'Monitor knee pain and consult if it persists.' },
  { keyword: 'shoulder pain', score: 5, next_step: 'Monitor shoulder pain and consult if it persists.' },
  { keyword: 'hip pain', score: 5, next_step: 'Monitor hip pain and consult if it persists.' },
  { keyword: 'ankle pain', score: 5, next_step: 'Monitor ankle pain and consult if it persists.' },
  { keyword: 'wrist pain', score: 5, next_step: 'Monitor wrist pain and consult if it persists.' },
  { keyword: 'elbow pain', score: 5, next_step: 'Monitor elbow pain and consult if it persists.' },
  { keyword: 'muscle pain', score: 5, next_step: 'Monitor muscle pain and consult if it persists.' },
  { keyword: 'joint pain', score: 5, next_step: 'Monitor joint pain and consult if it persists.' },
  { keyword: 'ache', score: 5, next_step: 'Monitor aches and consult if they persist.' },
  { keyword: 'aching', score: 5, next_step: 'Monitor aching and consult if it persists.' },
  { keyword: 'soreness', score: 5, next_step: 'Monitor soreness and consult if it persists.' },
  { keyword: 'sore', score: 5, next_step: 'Monitor soreness and consult if it persists.' },
  { keyword: 'tender', score: 5, next_step: 'Monitor tenderness and consult if it persists.' },
  { keyword: 'tenderness', score: 5, next_step: 'Monitor tenderness and consult if it persists.' },
  { keyword: 'discomfort', score: 5, next_step: 'Monitor discomfort and consult if it persists.' },
  { keyword: 'uncomfortable', score: 5, next_step: 'Monitor discomfort and consult if it persists.' },
  { keyword: 'tight', score: 5, next_step: 'Monitor tightness and consult if it limits function.' },
  { keyword: 'tightness', score: 5, next_step: 'Monitor tightness and consult if it limits function.' },
  { keyword: 'strain', score: 5, next_step: 'Monitor strain and consult if it persists.' },
  { keyword: 'sprain', score: 5, next_step: 'Monitor sprain and consult if it worsens.' },
  { keyword: 'pulled muscle', score: 5, next_step: 'Monitor pulled muscle and consult if severe.' },
  { keyword: 'muscle strain', score: 5, next_step: 'Monitor muscle strain and consult if it persists.' },
  { keyword: 'cramp', score: 5, next_step: 'Monitor cramps and consult if frequent or severe.' },
  { keyword: 'cramping', score: 5, next_step: 'Monitor cramping and consult if frequent or severe.' },
  { keyword: 'spasm', score: 5, next_step: 'Monitor spasms and consult if frequent or severe.' },
  { keyword: 'muscle spasm', score: 5, next_step: 'Monitor muscle spasms and consult if frequent.' },
  { keyword: 'limited range', score: 5, next_step: 'Monitor range of motion and consult if not improving.' },
  { keyword: 'limited movement', score: 5, next_step: 'Monitor movement and consult if not improving.' },
  { keyword: 'difficulty moving', score: 5, next_step: 'Monitor movement and consult if not improving.' },
  { keyword: "can't move", score: 5, next_step: 'Monitor movement and consult if severe.' },
  { keyword: 'plantar fasciitis', score: 5, next_step: 'Consult a physiotherapist for treatment options.' },
  { keyword: 'tennis elbow', score: 5, next_step: 'Consult a physiotherapist for treatment.' },
  { keyword: "golfer's elbow", score: 5, next_step: 'Consult a physiotherapist for treatment.' },
  { keyword: 'chest congestion', score: 5, next_step: 'Monitor and consult if persistent or worsening.' },
  { keyword: 'stomach pain', score: 5, next_step: 'Monitor stomach pain and consult if persistent.' },
  { keyword: 'belly pain', score: 5, next_step: 'Monitor abdominal pain and consult if persistent.' },
  { keyword: 'bloating', score: 5, next_step: 'Monitor bloating and consult if persistent.' },
  { keyword: 'indigestion', score: 5, next_step: 'Monitor indigestion and consult if frequent.' },
  { keyword: 'heartburn', score: 5, next_step: 'Monitor heartburn and consult if frequent or severe.' },
  { keyword: 'acid reflux', score: 5, next_step: 'Monitor reflux and consult if frequent or severe.' },
  { keyword: 'diarrhea', score: 5, next_step: 'Monitor and consult if persistent or severe.' },
  { keyword: 'constipation', score: 5, next_step: 'Monitor and consult if prolonged.' },
  { keyword: 'insomnia', score: 5, next_step: 'Discuss sleep difficulties with your healthcare provider.' },
  { keyword: "can't sleep", score: 5, next_step: 'Discuss sleep difficulties with your healthcare provider.' },
  { keyword: 'exhausted', score: 5, next_step: 'Monitor exhaustion and consult if persistent.' },
  { keyword: 'tired all the time', score: 5, next_step: 'Consult a healthcare provider about persistent fatigue.' },
  { keyword: 'no energy', score: 5, next_step: 'Monitor energy levels and consult if concerning.' },
  { keyword: 'lethargy', score: 5, next_step: 'Monitor and consult if persistent lethargy.' },
  { keyword: 'anxiety', score: 5, next_step: 'Consider speaking with a mental health professional.' },
  { keyword: 'mood swings', score: 5, next_step: 'Consider discussing mood changes with a healthcare provider.' },
  { keyword: 'irritable', score: 5, next_step: 'Monitor mood changes and consider professional support.' },
  { keyword: 'stressed', score: 5, next_step: 'Consider stress management techniques or professional support.' },
  { keyword: 'redness', score: 5, next_step: 'Monitor skin changes and consult if persistent.' },
  { keyword: 'irritation', score: 5, next_step: 'Monitor skin irritation and consult if worsening.' },
  { keyword: 'itching', score: 5, next_step: 'Monitor itching and consult if severe or persistent.' },
  { keyword: 'itchy', score: 5, next_step: 'Monitor itching and consult if severe or persistent.' },
  { keyword: 'burning skin', score: 5, next_step: 'Monitor skin symptoms and consult if concerning.' },
  { keyword: 'fever', score: 5, next_step: 'Monitor fever and consult if high or persistent.' },
  { keyword: 'chills', score: 5, next_step: 'Monitor and consult if accompanied by other symptoms.' },
  { keyword: 'sweating', score: 5, next_step: 'Monitor sweating patterns and consult if concerning.' },
  { keyword: 'weight gain', score: 5, next_step: 'Monitor weight changes and discuss with healthcare provider.' },
  { keyword: 'appetite loss', score: 5, next_step: 'Monitor appetite changes and consult if persistent.' },
  { keyword: 'loss of appetite', score: 5, next_step: 'Monitor appetite changes and consult if persistent.' },
];

interface AnalysisResult {
  red_flag_detected: boolean;
  confidence_score: number;
  matched_symptom: string | null;
  matched_score: number | null;
  suggested_next_step: string;
}

export interface RealTimeAnalysisResult {
  detected: boolean;
  severity: number;
  matchedKeywords: string[];
  needsProfessionalAlert: boolean;
}

export function analyzeSymptomRealTime(text: string): RealTimeAnalysisResult {
  if (!text.trim()) {
    return { detected: false, severity: 0, matchedKeywords: [], needsProfessionalAlert: false };
  }

  const lower = text.toLowerCase();
  let highestScore = 0;
  const matched: string[] = [];

  for (const item of RED_FLAG_KEYWORDS) {
    if (lower.includes(item.keyword)) {
      if (!matched.includes(item.keyword)) {
        matched.push(item.keyword);
      }
      if (item.score > highestScore) {
        highestScore = item.score;
      }
    }
  }

  return {
    detected: matched.length > 0,
    severity: highestScore,
    matchedKeywords: matched,
    needsProfessionalAlert: highestScore >= 7,
  };
}

export function analyzeSymptomLocal(description: string): AnalysisResult {
  const lower = description.toLowerCase();
  let highestScore = 0;
  let matchedKeyword: string | null = null;
  let matchedNextStep = '';

  for (const item of RED_FLAG_KEYWORDS) {
    if (lower.includes(item.keyword) && item.score > highestScore) {
      highestScore = item.score;
      matchedKeyword = item.keyword;
      matchedNextStep = item.next_step;
    }
  }

  if (highestScore >= 6) {
    return {
      red_flag_detected: true,
      confidence_score: highestScore / 10,
      matched_symptom: matchedKeyword,
      matched_score: highestScore,
      suggested_next_step: matchedNextStep,
    };
  }

  return {
    red_flag_detected: false,
    confidence_score: highestScore / 10,
    matched_symptom: matchedKeyword,
    matched_score: matchedKeyword ? highestScore : null,
    suggested_next_step:
      'Continue your current treatment plan and monitor your symptoms. Book a follow-up if symptoms persist or worsen.',
  };
}
